services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    env_file: 
      - ./backend/.env
    depends_on:
      - db
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app

  db:
    image: postgres:15
    volumes: 
      - stratcheck_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

volumes:
  stratcheck_data: